### ISSUE TITLE
[TODO]

### ISSUE THREAD

**Issue by sihyeong671** [sihyeong671/AID_WEB#27]
- [x] enter 버튼 누를시 제출되는 현상 제거하기 - 정지민
- [x] read, read_all test코드 작성하기 - 정지민
- [x] aws, githubaction으로 연결 - 박시형
- [x] 환경설정 에러 해결하기 - 김정민, 이서연
- [x] submissionlist, submissiondetail 페이지, api 제작 만들기
