### ISSUE TITLE
[TODO] Study 게시판 API 제작

### ISSUE THREAD

**Issue by lijm1358** [sihyeong671/AID_WEB#86]
* 스터디 생성, 모집용 게시판 api 제작
* TODOs
  * [x] 스터디 scheme 제작
  * [x] 스터디 CRUD
    * [x] 생성, 조회, 삭제(팀장만), 수정(팀장만. 내용, 상태, 권한, 강퇴)
    * [x] 팀원 탈퇴, 팀장 탈퇴(owner 자동 변경)
    * [x] 스터디 신청, 팀장 승인
